# Generated by Django 4.2.8 on 2023-12-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvestmentModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.IntegerField()),
                ("price", models.CharField(max_length=100)),
                ("sum", models.CharField(max_length=100)),
                ("user_id", models.CharField(max_length=100)),
            ],
        ),
    ]
