# Generated by Django 4.2.8 on 2024-01-14 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("etf", "ETF"),
                            ("stock", "Stock"),
                            ("commodity", "Commodity"),
                        ],
                        default=("stock", "Stock"),
                        max_length=50,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("eur", "EUR"), ("usd", "USD"), ("gbp", "GBP")],
                        default=("usd", "USD"),
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("closed", "Closed"),
                        ],
                        default=("active", "Active"),
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dividends_interest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
